version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-west-2
    AWS_ACCOUNT_ID: "012918245028"
    ECR_REPO: myapp
    CLUSTER_NAME: democlusterlondon
    SERVICE_NAME: my-taskdef-service-4q4hy87h
    CONTAINER_NAME: my-container

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION |
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO:latest

 post_build:
  commands:
    - echo Updating ECS service...
    - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
